version: '3.9'

services: 
  djangoapp: 
    container_name: LooseTheLeftovers_Backend
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_HOST=${PG_HOST}
    depends_on:
      - db
    volumes:
      - .:/src  # This mounts the current directory to /src in the container

  db: 
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
